<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Catalogue')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet('https://bootswatch.com/3/flatly/bootstrap.min.css')
            ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        Catalogue
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Accueil</a></li>
                        <li><a href="<?= $this->url('cart') ?>">Panier</a></li>
                        <li><a href="<?= $this->url('catalogue') ?>">Produits</a></li>
                    </ul>

                    <form class="navbar-form navbar-right">
                        <div class="form-group">
                            <label for="username">Login</label>
                            <input id="username" name="username" type="text" placeholder="Login" class="form-control" />
                            <label for="password">Mot de passe</label>
                            <input id="password" name="password" type="password" placeholder="Mot de passe" class="form-control"/>
                            <button class="btn btn-go btn-primary">Se connecter</button>
                        </div>
                    </form>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer class="container-fluid jumbotron">
                <div class="row">
                    <div class="col-md-4 col-sm-6 footer-navigation">
                        <h2>Liens rapides</h2>
                        <ul>
                            <li>
                                <a href="#">Accueil</a>
                            </li>
                            <li>
                                <a href="/cart">Panier
                                    <i class="fa fa-shopping-cart"></i>
                                </a>
                            </li>
                            <li>
                                <a href="/login">Connexion</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 col-sm-6 footer-contacts">
                        <h2>Nous contacter</h2>
                        <ul>
                            <li>
                                <i class="fa fa-map-marker"></i> UQAC, Québec, Canada</li>
                            <li>
                                <i class="fa fa-phone"></i> +1 418 545 5011</li>
                            <li>
                                <i class="fa fa-envelope"></i> catalogue@uqac.ca</li>
                        </ul>
                    </div>
                    <div class="col-md-4 footer-about">
                        <h2>Catalogue en ligne</h2>
                        <p>Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula
                            sit amet.</p>
                    </div>
                </div>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
