<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <?php if (!isset($this->previous)): ?>
            <li class="disabled">
                <a>&laquo;</a>
                <a>&lsaquo;</a>
            </li>
        <?php else: ?>
            <li>
                <a href="<?= $this->url($this->route, [], ['query' => ['page' => $this->first]]); ?>">&laquo;</a>
                <a href="<?= $this->url($this->route, [], ['query' => ['page' => $this->previous]]); ?>">&lsaquo;</a>
            </li>
        <?php endif; ?>
        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page == $this->current): ?>
                <li class="active">
                    <a><?= $page ?></a>
                </li>
            <?php else: ?>
                <li>
                    <a href="<?= $this->url($this->route, [], ['query' => ['page' => $page]]); ?>">
                        <?= $page; ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    
        <?php if (!isset($this->next)): ?>
            <li class="disabled">
                <a>&rsaquo;</a>
                <a>&raquo;</a>
            </li>
        <?php else: ?>
            <li>
                <a href="<?= $this->url($this->route, [], ['query' => ['page' => $this->next]]); ?>">&rsaquo;</a>
                <a href="<?= $this->url($this->route, [], ['query' => ['page' => $this->last]]); ?>">&raquo;</a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>