<div class="jumbotron container page-detail">

    <?php 
    
        $product = $this->product ; 

        $cart = [
            'id' => $product->getId(),
            'nom' => $product->getNom(),
            'photo' => $product->getPhoto(),
            'prix' => $product->getPrix(),
            'quantite' => 1,
        ] ; 
    ?>
    <h1><?= $product->getNom() ?>

    <div class="row">
        <div class="col-md-3">
            <img src="../../img/products/<?= $product->getPhoto() ?>" />
        </div>

        <div class="col-md-9">
            <h2>Description du produit</h2>
            <p>
                <?= $product->getDescription() ?>
            </p>

            <h2>Prix</h2>
            <p>
               <?= $product->getPrix() ?> $ 
                <button class="btn btn-primary" onclick='addToCart(<?php echo (json_encode($cart)) ?>)'>Ajouter au panier <i class="fa fa-cart-plus"></i>"</button>
            </p>
        </div>
    </div>
</div>

<script src="../../js/script.js"></script>