<section class="container">
    <?php foreach ($this->products as $product): ?>
    <?php 
        $cart = [
            'id' => $product->getId(),
            'nom' => $product->getNom(),
            'photo' => $product->getPhoto(),
            'prix' => $product->getPrix(),
            'quantite' => 1,
         ] ;
    ?>
    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $product->getNom() ?></h3>
            </div>
            <div class="panel-body row">
                <div class="col-md-3">
                    <img src="<?= $product->getPhoto() ?>"/>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            Prix : <?= $product->getPrix() ?> <i class="fa fa-usd"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <p><?= $product->getDescription() ?></p>
                    <a href="./products/<?= $product->getId() ?>" class="btn btn-info">Fiche produit</a>
                    <button class="btn btn-primary" onclick='addToCart(<?php echo (json_encode($cart)) ?>)' >Ajouter au panier <i class="fa fa-cart-plus"></i></button>
                </div>
                        
            </div>
        </div>
    </div>

    <?php endforeach; ?>
</section>

<script>
    // GESTION DES COOKIES
    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        var expires = "expires="+d.toUTCString();
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    function getCookie(cname) {
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for(var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    // AJOUT 
    function addToCart(produit) {
        var produit = JSON.stringify(produit) ;
        console.log(produit);
        // On vérifie s'il y a déjà des produits dans le panier
        var cart = getCookie('cart') 
        if (cart == "") { // Le cookie n'a pas encore été créé
            setCookie('cart',produit,7) ;
        } else { // Cookie existant
            var oldCart = cart ; // On récupère la valeur existante
            setCookie('cart','',-1) ;//On supprime le cookie
            setCookie('cart',oldCart + "," + produit,7) ; //On créée le nouveau
        }
        /*console.log(produit);
        var d = new Date() ;
        d.setTime(d.getTime() + (7*24*60*60*1000)) ;
        document.cookie = 'cart =' + JSON.stringify(produit) + ';' + d + ";path=/"; */
    }
</script>