<section class="container">
    <?php foreach ($this->products as $product): ?>

    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $product->getNom() ?></h3>
            </div>
            <div class="panel-body row">
                <div class="col-md-3">
                    <img src="<?= $product->getPhoto() ?>"/>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            Prix : <?= $product->getPrix() ?> <i class="fa fa-usd"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <p><?= $product->getDescription() ?></p>
                    <a href="./products/<?= $product->getId() ?>" class="btn btn-info">Fiche produit</a>
                    <button class="btn btn-primary" >Ajouter au panier <i class="fa fa-cart-plus"></i></button>
                </div>
                        
            </div>
        </div>
    </div>

    <?php endforeach; ?>
</section>