<?php


 $title = 'Mes produits';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('catalogue', array('action'=>'add'));?>">Ajouter un nouveau produit</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($products as $product) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($product->getNom());?></td>
     <td><?php echo $this->escapeHtml($product->getPhoto());?></td>
     <td><?php echo $this->escapeHtml($product->getDescription());?></td>
     <td><?php echo $this->escapeHtml($product->getPrix());?></td>
     <td>
         <a href="<?php echo $this->url('catalogue',
             array('action'=>'edit', 'id' => $product->getId()));?>">Edit</a>
         <a href="<?php echo $this->url('catalogue',
             array('action'=>'delete', 'id' => $product->getId()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>