<main id="page-cart">
    <div class="jumbotron container">
        <table class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Photo</th>
                    <th>Prix</th>
                    <th>Quantité</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                <?php $total = 0 ; foreach ($this->carts as $cart): ?>
                    <tr>
                        <td><?= $cart->getNom() ?></td>
                        <td><img src="img/products/<?= $cart->getPhoto() ?>" /></td>
                        <td><?= $cart->getPrix() ?> $</td>
                        <td><?= $cart->getQuantite() ?></td>
                        <td><?= $cart->getTotal() ?> $</td>
                    </tr>
                <?php $total += $cart->getTotal() ; endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4" class="text-right">Total du panier</td>
                    <td><?php echo $total ; ?> $</td>
                </tr>
            </tfoot>
        </table>
    </div>
</main>