<main id="page-cart">
    <div class="jumbotron container">
        <table class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Photo</th>
                    <th>Prix</th>
                    <th>Quantité</th>
                    <th>Total</th>
                </tr>
            </thead>
            <?php $total = 0 ;  if ($this->carts != "") : ?>
                <tbody>
                    <?php foreach ($this->carts as $cart): ?>
                        <tr>
                            <td><?= $cart->getNom() ?></td>
                            <td><img src="img/products/<?= $cart->getPhoto() ?>" /></td>
                            <td><?= $cart->getPrix() ?> $</td>
                            <td><?= $cart->getQuantite() ?></td>
                            <td><?= $cart->getTotal() ?> $</td>
                        </tr>
                    <?php $total += $cart->getTotal() ; endforeach;?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4" class="text-right"><strong>Total du panier :</strong></td>
                        <td><?php echo $total ; ?> $</td>
                    </tr>
                    <tr>
                        <td colspan="5" class="text-right">
                            <button class="btn btn-primary" onclick="deleteCart()">Supprimer mon panier <i class="fa fa-times"></i></button>
                            <button class="btn btn-info" onclick="">Passer au paiement <i class="fa fa-credit-card"></i></button>
                        </td>
                    </tr>
                </tfoot>
            <?php else : ?>
                <tbody>
                    <tr>
                        <td colspan="5" class="text-center">Vous n'avez aucun produit dans votre panier.</td>
                    </tr>
                </tbody>
            <?php endif; ?>   
        </table>
    </div>
</main>

<script src="./js/script.js"></script>